name: Build Cyd

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run make-dev

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cyd-${{ matrix.os }}
          path: out/**
          if-no-files-found: warn
